version: "3.0"
services:
  web:
    image: nginx
    volumes:
      - ../www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - ENVIREMENT=development

    links:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ../www:/var/www/html
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 100M
        reservations:
          cpus: '0.15'
          memory: 40M
    links:
      - db

  db:
    image: mysql
    command: "--innodb_use_native_aio=0"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ../db:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 100M
        reservations:
          cpus: '0.15'
          memory: 40M
    ports:
      - "3306:3306"
