version: "3"
services:
  web:
    image: nginx
    volumes:
      - ../code:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - ENVIREMENT=development

    links:
      - php

  php:
    dns:
      - 8.8.8.8
      - 9.9.9.9
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ../code:/var/www/html
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 100M
        reservations:
          cpus: '0.15'
          memory: 40M
    links:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ../db/mysql:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 100M
        reservations:
          cpus: '0.15'
          memory: 40M
    ports:
      - "3306:3306"

  #PostgreSQL:
    #restart: always
    #image: sameersbn/postgresql:9.6-2
    #ports:
      #- "5432:5432"
    #environment:
      #- DEBUG=false

      #- DB_USER=drupal
      #- DB_PASS=drupal
      #- DB_TEMPLATE=
      #- DB_EXTENSION=
      #- PGDATA = C:\Users\Daiane\Documents\docker\drupal\postgre
      #- POSTGRES_PASSWORD=root

      #- REPLICATION_MODE=
      #- REPLICATION_USER=
      #- REPLICATION_PASS=
      #- REPLICATION_SSLMODE=
    #volumes:
      #- ../postgre:/var/lib/postgresql


    
    